// SPDX-FileCopyrightText: 2026 Foundation Devices, Inc. <hello@foundation.xyz>
// SPDX-License-Identifier: GPL-3.0-or-later

import { Palette, Size, Importance } from "../../compat/theme.slint";
import {
    AppHeader, BasePage, PageBody, ContentSection, ButtonSection, Button,
    HeadingMd, TextMd, TextSm,
} from "../../compat/widgets.slint";
import { Callbacks } from "../../callbacks.slint";
import { ApprovalProps } from "./props.slint";

export component ApprovalPage inherits BasePage {
    in property <ApprovalProps> props;

    VerticalLayout {
        AppHeader {
            title: Callbacks.approval.title;
            side-padding: Size.sz8;
        }

        PageBody {
            ContentSection {
                spacing: Size.sz4;

                VerticalLayout {
                    spacing: Size.sz1;
                    TextSm {
                        text: "Website";
                        color: Palette.content-tertiary;
                    }
                    HeadingMd {
                        text: Callbacks.approval.origin;
                    }
                }

                VerticalLayout {
                    spacing: Size.sz1;
                    TextSm {
                        text: "Username";
                        color: Palette.content-tertiary;
                    }
                    TextMd {
                        text: Callbacks.approval.username;
                        color: Palette.content-primary;
                    }
                }
            }

            ButtonSection {
                Button {
                    label: "Reject";
                    importance: Importance.normal;
                    clicked => {
                        Callbacks.reject();
                    }
                }
                Button {
                    label: Callbacks.approval.action-label;
                    importance: Importance.primary;
                    clicked => {
                        Callbacks.approve();
                    }
                }
            }
        }
    }
}
